### PR TITLE
jQuery upgrade v.3.3.1

### PR DESCRIPTION
**Pull request by BrunildaDosti**
https://mantis.phplist.org/view.php?id=19755

### CODE REVIEW

**Comment by samtuke** [comment]
Thanks Brunilda, I have reviewed the PR. It looks like Bootstrap was also upgraded in this PR, is that correct?

Please can you provide more information on how jQuery files location has changed in this PR? Have the jQuery files been centralised? Are there still two copies - one in core and one in the bootlist/trevelin theme?

**Comment by samtuke** [comment]
I will merge this to ease continued testing

**Comment by BrunildaDosti** [comment]
Hi Sam,

Yes, you`re correct. Bootstrap was upgraded to v.3.3.7 as jQuery 3.x was not compatible with Bootstrap 3.3.6(old version of phpList3).

The directories modified for this jQuery upgrade are:

-admin\ui\phplist-ui-bootlist 
-admin\js (jQueryUI)

There was a list of deprecated functionality.
Please find attached a guide with all the steps proceeded for jQuery Upgrade.

Thanks,
[Steps for upgrading jQuery version to the latest version.pdf](https://github.com/phpList/phplist-ui-bootlist/files/2922530/Steps.for.upgrading.jQuery.version.to.the.latest.version.pdf)

**Comment by samtuke** [comment]
That's very clear and helpful - thanks!

**Comment by bramley** [comment]
@BrunildaDosti  @samtuke  You also need to consider the Dressprow theme, which still refers to jquery 1.7.1 and jquery-ui 1.8.1.

**Comment by samtuke** [comment]
And also the jQuery copy used for public pages, as reported here: https://discuss.phplist.org/t/jquery-version-1-5-2/4957/5?u=samtuke

**Pull request merged**
