### PR TITLE
Create fallback handling for jQuery UI async tabs

### PR DESCRIPTION
**Pull request by xh3n1**
The Bootstrap theme is migrating all jQuery UI tabs to Bootstrap tabs. Bootstrap tabs have by default, however, no support for async loading.
This code adds a new async loading behavior for the Bootstrap tabs. Thus they work just like they do in the old theme.

The patch here involves some Javascript tricks due to the way Bootstrap tabs are implemented. Basically:
1. We need to convert all URIs to valid identifiers (Bootstrap accesses them as an identifier, some characters such as ? are not permitted there)
2. This leads to the fact that we need a hashmap storing the relationship of identifier => URL
3. A new DOM element is created that contains a loading status
4. If the data is loaded, the DOM element is replaced with the response
5. Due to the fact that myfunction does a lot of formatting, I had to move all functions with side effect outside of it.

Signed-off-by: Xheni Myrtaj <myrtajxheni@gmail.com>

### CODE REVIEW

**Comment by xh3n1** [comment]
@mariez We need this for this PR: https://github.com/phpList/phplist3/pull/356 . I need to load content via ajax on these tabs and that cannot be done because some  URIs are not valid identifiers since some characters such as ? are not permitted.

**Comment by mariez** [comment]
Thanks @xh3n1. I understand then that both PR are parts of the same work. As @michield  will merge that PR to phplist3 then I think he should decide on this too.

**Comment by mariez** [comment]
@xh3n1 you need to update this branch with the reset icon change

**Comment by xh3n1** [comment]
Thanks @mariez . I rebased it to master.

**Pull request merged**
