### PR TITLE
Edited button on template page

### PR DESCRIPTION
**Pull request by BrunildaDosti**
Center action button symbols on Templates page

### CODE REVIEW

**Comment by samtuke** [comment]
@BrunildaDosti Shouldn't these changes be made to the Less files instead of the minified CSS?

**Comment by BrunildaDosti** [comment]
> @BrunildaDosti Shouldn't these changes be made to the Less files instead of the minified CSS?

@samtuke @xh3n1 
Done. Please check it.

**Comment by samtuke** [comment]
@BrunildaDosti Please can you attach a screenshot so I can compare how this renders in my local testing?

**Comment by BrunildaDosti** [comment]
> @BrunildaDosti Please can you attach a screenshot so I can compare how this renders in my local testing?

Screenshot attached:

**Comment by BrunildaDosti** [comment]
> > @BrunildaDosti Please can you attach a screenshot so I can compare how this renders in my local testing?
> 
> @samtuke
> Screenshot attached:
> 

@Sam,
Please take the latest stylesheets push on Git.
(Before grunt less was done with one warning, now successfully!)

**Comment by samtuke** [comment]
@BrunildaDosti The horizontal positioning looks good now, but the vertical positioning of the symbols in Firefox and Chrome is not centered in my testing like it is in your screenshot.
Workspace 1_563

**Comment by BrunildaDosti** [comment]
> @BrunildaDosti The horizontal positioning looks good now, but the vertical positioning of the symbols in Firefox and Chrome is not centered in my testing like it is in your screenshot.
> Workspace 1_563

@samtuke 
The centralize of glyphicon is done by adding the lines into base.less file.

span.glyphicon.glyphicon-eye-open,
span.glyphicon.glyphicon-edit,
span.glyphicon.glyphicon-trash {
	top:0px;
}
After this, generated stylesheet file through _grunt less_

Please, let me know if you have any other questions.

**Comment by samtuke** [comment]
@BrunildaDosti Thanks. The glyphicons on the List Subscribers page, which were correctly positioned before, are now not vertically aligned -- spacing has increased.
Workspace 1_564

**Comment by BrunildaDosti** [comment]
> @BrunildaDosti Thanks. The glyphicons on the List Subscribers page, which were correctly positioned before, are now not vertically aligned -- spacing has increased.
> Workspace 1_564

I solved it by:
-adding a class to delete class in templates.php (
The PR:
https://github.com/phpList/phplist3/pull/519 )
-styling this class for delete button in template list page.

Please let me know for any questions.

**Pull request merged**
