### PR TITLE
Added a jQuery function which add css changes on click event

### PR DESCRIPTION
**Pull request by BrunildaDosti**
@suelaP 
Added a class selector only for minitabs in campaign list page.

Let me know for any questions.

### CODE REVIEW

**Comment by samtuke** [comment]
@BrunildaDosti Most of the changes in this PR seem to be related to jQuery compatibility rather than the new function referred to in the description. Is this intentional?

**Comment by BrunildaDosti** [comment]
> @BrunildaDosti Most of the changes in this PR seem to be related to jQuery compatibility rather than the new function referred to in the description. Is this intentional?

@samtuke No, this is not intentional.
The only intentional changes are: 486-495 lines in js/phpList3ToBootstrap.js file. 

Please, let me push again the changes.

**Comment by samtuke** [comment]
@BrunildaDosti OK thanks

**Comment by BrunildaDosti** [comment]
> @BrunildaDosti OK thanks

@samtuke Please reject this PR! Sorry for the confusion.
The new PR related with this:
https://github.com/phpList/phplist-ui-bootlist/pull/101

**Pull request closed without merging**
