### PR TITLE
Trigger change event at send campaigns page.

### PR DESCRIPTION
**Pull request by BrunildaDosti**
Added a JS function to return prompt only if user has done changes on inputs(check boxes, messages...etc), for any reasons leaves the page and navigate to sidebar menu.

### CODE REVIEW

**Comment by samtuke** [comment]
@brunilda are the changes to the footer files intentional?

**Comment by BrunildaDosti** [comment]
> @Brunilda are the changes to the footer files intentional?

Sorry! They are not intentional. The only file edited is js/phpList3ToBootstrap.js file.
--

**Review by BrunildaDosti — COMMENTED** [review]
Added function is the one with comment:
/* function to prevent leave page */

**Comment by xh3n1** [comment]
@BrunildaDosti You have included a commit that is already in master branch.
I would suggest rebasing by the following workflow 😉 
```
git checkout master
git pull origin master
git checkout trigger-change-event-send-campaigns
git rebase origin/master
git push origin trigger-change-event-send-campaigns 
```

**Review by xh3n1 — CHANGES_REQUESTED** [review]
Please minify JavaScript :)

**Comment by BrunildaDosti** [comment]
> @BrunildaDosti You have included a commit that is already in master branch.
> I would suggest rebasing by the following workflow 😉
> 
> ```
> git checkout master
> git pull origin master
> git checkout trigger-change-event-send-campaigns
> git rebase origin/master
> git push origin trigger-change-event-send-campaigns 
> ```

@xh3n1  Done!
Did git reset and than restores the stashed changes as the push failed due to the tip of branch was behind.

Let me know how it goes.

**Review by xh3n1 — APPROVED** [review]

**Comment by xh3n1** [comment]
If the CKEditor is enabled, it will not ask "are you sure you want to leave.." if you made changes in the content area, otherwise works great.

**Comment by BrunildaDosti** [comment]
@samtuke @xh3n1 
Status of this PR: Paused
The function which checks trigger change for all inputs, should be updated to check  also the content from CKeditor.

**Pull request closed without merging**
