### PR TITLE
Remove double row striping on templates page

### PR DESCRIPTION
**Pull request by samtuke**
Remove border designed to emphasise grouping of two rows together on the 'List Templates' page, because this page now uses single-row layout due to the related PR in phpList3: https://github.com/phpList/phplist3/pull/516

### CODE REVIEW

**Comment by xh3n1** [comment]
@samtuke I think you should rebase to master.

**Review by xh3n1 — COMMENTED** [review]
I think you should rebase to master.

**Comment by samtuke** [comment]
@xh3n1 I think I did before, and did again now (no change). What's missing?

**Comment by xh3n1** [comment]
Did you try this workflow?  
`git checkout master`
`git pull origin master`
`git checkout remove-double-row-striping-on-templates-page`
`git rebase origin/master`
`git push origin -f remove-double-row-striping-on-templates-page`

**Comment by samtuke** [comment]
@xh3n1 yes, without the -f flag. Why is 'force' necessary?

**Comment by xh3n1** [comment]
@samtuke It deletes the previous commits and pushes your current one in the remote branch.

**Comment by samtuke** [comment]
@xh3n1 Yes but why would it be necessary to use it in this case? It should only be necessary for rewriting the history.

**Comment by xh3n1** [comment]
This branch has merge conflicts now as well.

**Pull request closed without merging**
