### PR TITLE
Remove row bottom border now that this table uses one row per element

### PR DESCRIPTION
**Pull request by samtuke**
Mantis: https://mantis.phplist.org/view.php?id=19913

### CODE REVIEW

**Comment by samtuke** [comment]
@brunilda is that comment just for future reference, or are you describing a problem?

**Comment by BrunildaDosti** [comment]
@samtuke I meant that change remove border bottom at rows, not only when has one row(as I understood from my review).

**Comment by samtuke** [comment]
Help me understand: is your comment a bug report relating to this PR?

**Comment by BrunildaDosti** [comment]
The PR says that border bottom should be removed only when is one row. 
Instead the changes remove the border bottom at all rows.

If your intention is to remove the border bottom at all, than the changes are ok.

**Pull request merged**
